

[platformio]
default_envs = LuftCheckNewDisplay

[env:LuftCheckNewDisplay]
platform = espressif32@6.8.1   ; nutzt Arduino-Core 2.0.17, sehr stabil
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
	wifwaf/MH-Z19@^1.5.3
	arduino-libraries/Arduino_JSON@^0.1.0
	esp32async/ESPAsyncWebServer @ ^3.8.1
  esp32async/AsyncTCP @ ^3.4.8
	knolleary/PubSubClient@^2.8
	sensirion/arduino-sht@^1.2.2
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library

build_flags =
  -D SPI_FREQUENCY=40000000 
	-D HW_v09c1
	-D SensorSHT
	-D LogoHTL
	-D Mirror
